
window.console=console||{log:function(x){}};var ipc=ipc||{};var _gaq=_gaq||[];if(!ipc.utils){ipc.utils=function(){var ga={trackers:{}},gaStash={events:[],customVars:{}},uTagMappings={_trackEvent:['ga_eventCategory','ga_eventAction','ga_eventLabel','ga_eventValue','ga_nonInteraction'],_trackSocial:['ga_socialNetwork','ga_socialAction','ga_socialTarget','ga_socialPagePath'],_trackPageview:['ga_page'],_setCustomVar:function(commands){var command={};command[commands[2]]=commands[3];gaStash.customVars[commands[2]]=commands[3];console.log(command);return command;}},comscoreRefreshCallbacks=[],deprecatedMethod=function(){console.log('Deprecated Method Call')};gaStash.events.parsed=false;return{ipcCreateCookie:function(name,value,days){var date,expires="";if(days){date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));expires="; expires="+date.toGMTString();}
document.cookie=name+"="+value+expires+"; path=/";},ipcReadCookie:function(name){var nameEQ=name+"=",ca=document.cookie.split(';'),i,caLength=ca.length,c;for(i=0;i<caLength;i+=1){c=ca[i];while(c.charAt(0)===' '){c=c.substring(1,c.length);}
if(c.indexOf(nameEQ)===0){return c.substring(nameEQ.length,c.length);}}
return null;},async_load:function(src){function async_load(){var s=document.createElement('script'),x=document.getElementsByTagName('script')[0];s.type='text/javascript';s.async=true;s.src=src;x.parentNode.insertBefore(s,x);}
if(window.attachEvent){window.attachEvent('onload',async_load);}
else{window.addEventListener('load',async_load,false);}},sendRequest:function(url,callback,postData){var req=ipc.utils.createXMLHTTPObject();if(!req)
return;var method=(postData)?"POST":"GET";req.open(method,url,true);if(typeof postData!=='undefined')
req.setRequestHeader('Content-type','application/x-www-form-urlencoded');req.onreadystatechange=function(){if(req.readyState!=4)
return;if(req.status!=200&&req.status!=304)
return;if(typeof callback!=='undefined')
callback(req);};if(req.readyState==4)
return;req.send(postData);},createXMLHTTPObject:function(){var xmlhttp=false;var XMLHttpFactories=[function(){return new XMLHttpRequest()},function(){return new ActiveXObject("Msxml2.XMLHTTP")},function(){return new ActiveXObject("Msxml3.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}];for(var i=0;i<XMLHttpFactories.length;i++){try{xmlhttp=XMLHttpFactories[i]();}catch(e){continue;}
break;}
return xmlhttp;},createConfigCookie:function(namespace,config,expireAfter){if(typeof(JSON)==='undefined'){ipc.utils.async_load('http://ajax.cdnjs.com/ajax/libs/json2/20110223/json2.js');}
ipc.utils.ipcCreateCookie(namespace,JSON.stringify(config),expireAfter);},deleteCookie:function(name){document.cookie=name+'=; expires=Thu, 01 Jan 1970 00:00:01 GMT;';},refreshCookie:function(){console.log("Unimplemented: Phase 2 function");},registerTracker:function(id,gaid){ga.trackers[id]=gaid;},customVarStack:gaStash.customVars,eventStack:gaStash.events,runEventStash:function(){if(gaStash.events.parsed)
return;console.log('Parsing event stash ('+gaStash.events.length+' events)');gaStash.events.parsed=true;var event,that=this,i=0;while(gaStash.events.length&&i<5){event=gaStash.events.shift();setTimeout(function(){that.gaMultiPush.apply(that,event);},(1100*(i+1)));++i;}},gaMultiPush:function(commandArray,trackers){var command,cfg,uid,allTrackerIds=[];if('undefined'===typeof utag||('undefined'!==typeof utag&&utag.handler.iflag!=1)){gaStash.events.push([commandArray,trackers]);if(typeof(console)==='object'&&typeof(console.log)==='function'){console.log('Cannot execute GA via Tealium because utag is undefined: Adding to event stash');}
if(typeof window.dataLayer=="undefined"){return false;}}
if(commandArray===null||commandArray===undefined){console.log('Call to gaMultiPush invalid: commandArray is null or undefined');return;}
if(trackers===undefined||!(trackers instanceof Array&&trackers.length>0)){trackers=null;}
cfg=uTagMappings[commandArray[0]];command={};if(typeof(cfg)==='function'){command=cfg(commandArray,trackers);}else{for(var i=0;i<cfg.length;++i){var val;if(typeof(commandArray[i+1])==='undefined')
val=null;else
val=commandArray[i+1];command[cfg[i]]=val;command[cfg[i]]=val;}}
command.ga_callTrackers=trackers;for(uid in ga.trackers){allTrackerIds.push(uid);}
if(commandArray[0]==='_trackPageview'){if(typeof utag!="undefined"&&typeof utag.view=="function"){utag.view(command,null,allTrackerIds);}
window.dataLayer=window.dataLayer||[];window.dataLayer.push({'event':'screen.load','data':command});}else{if(typeof utag!="undefined"&&typeof utag.link=="function"){utag.link(command,null,allTrackerIds);}
window.dataLayer=window.dataLayer||[];window.dataLayer.push({'event':'element.click','data':command});}},trackTiming:deprecatedMethod,pushGaqTrackers:deprecatedMethod,trackEvent:function(category,action,label,value,trackers,nonInteraction){if(typeof nonInteraction==='undefined')
nonInteraction=true;ipc.utils.gaMultiPush(['_trackEvent',category,action,label,value,nonInteraction],trackers);if(this.hasTimeincAnalytics()){window.timeinc.analytics.trackEvent({category:category,action:action,label:label,value:value,interaction:!nonInteraction})}},trackSocial:function(network,socialAction,opt_target,opt_pagePath,trackers){ipc.utils.gaMultiPush(['_trackSocial',network,socialAction,opt_target,opt_pagePath],trackers);if(this.hasTimeincAnalytics()){window.timeinc.analytics.trackSocial({network:network,action:socialAction,url:opt_target});}},trackPageView:function(url,path,prop){if(typeof path!=="undefined"){ipc.utils.gaMultiPush(['_trackPageview',path],false);if(this.hasTimeincAnalytics()){window.timeinc.analytics.recordPageView(false,path);}}else{ipc.utils.gaMultiPush(['_trackPageview'],false);if(this.hasTimeincAnalytics()){window.timeinc.analytics.recordPageView(false);}}
ipc.utils.comscorePageView();},setCustomVar:function(index,name,value,opt_scope,trackers){if(typeof(opt_scope)==='undefined'||!opt_scope){ipc.utils.gaMultiPush(['_setCustomVar',index,name,value],trackers);}
else{ipc.utils.gaMultiPush(['_setCustomVar',index,name,value,opt_scope],trackers);}},comscorePageView:function(){for(var i=0;i<comscoreRefreshCallbacks.length;++i){comscoreRefreshCallbacks[i]();}},comscore:{registerRefreshCallback:function(callback){comscoreRefreshCallbacks.push(callback);}},comscoreSetId:function(){console.log('comscoreSetId is deprecated');},hasTimeincAnalytics:function(){return("undefined"!==typeof window.timeinc)&&("undefined"!==typeof window.timeinc.analytics);}};}();}
var ipcReadCookie=ipc.utils.ipcReadCookie,ipcCreateCookie=ipc.utils.ipcCreateCookie
ipcSetupTracker=function(){console.log('Deprecated Method Call: ipcSetupTracker')},ipcSetupCustomVars=function(){console.log('Deprecated Method Call: ipcSetupTracker')};if(typeof(JSON)==='undefined'){ipc.utils.async_load('http://ajax.cdnjs.com/ajax/libs/json2/20110223/json2.js');}
if(typeof Array.prototype.indexOf!=="function"){Array.prototype.indexOf=function(obj,start){var i=(start||0),j=this.length;for(i;i<j;i++){if(this[i]===obj){return i;}}
return-1;}}